### ISSUE TITLE
Unable to locate data for Top Incomes

### ISSUE THREAD

**Issue by coding-to-music** [yaph/ipython-notebooks#1]
I would like to try out the notebook 
http://ramiro.org/notebook/top-incomes-share/
but I am unable to replicate the data in file 'csv/top-incomes.xlsx'
It perhaps was originally sourced from https://wid.world/data/
But the many ways to slice and dice it there makes it impossible to figure out how to recreate the data needed to use the really nice notebook you wrote. If you could upload the data file that would be really great. Thanks

**Comment by yaph** [comment]
Hi Tom, I don't include the data in this repo to avoid copyright issues. There is another GitHub repo where you can get the respective sheet as a CSV file https://github.com/datasets/world-wealth-and-income-database/blob/master/data/data.csv

I can also send you the file I used by email if you wish. Just let me know.

**Comment by coding-to-music** [comment]
Hi yes if you could send the file thanks very much!!

**Comment by yaph** [comment]
I just sent to to the address on your profile page.

**Comment by coding-to-music** [comment]
Thanks very much!
